language: node_js
node_js:
  - "0.10"
cache: false

env:
  global:
    - secure: "hC+CqFEIBsEZx8xjIPA5iHuo47DRdYF5+zpSIm7n4WUJ6hw123/oFEhKoD2spZuN9PBLGNjDQZ+Vjtvj2J6jp92OmuQrNp+jXMwwOtrV7TwjHMS3Bsrp1BcpLgcBeTT5XiZEA8NWYCFuK1EYK59GJ1j1ftQsz0dEHrnmpvy500w=" #Github Token

install:
  - gem install scss-lint --no-ri --version '=0.23.1'
  - scripts/setup

script:
  - scss-lint .
  - grunt && ./scripts/travis_artifacts.sh
